### PR TITLE
Small fix for those using -Wsign-conversion

### PR DESCRIPTION
**Pull request by igaztanaga**

### CODE REVIEW

**Comment by LeonineKing1199** [comment]
What's the likelihood of this being merged? Unordered right now has a lot of output from `-Wconversion` + `tuple.hpp` and this PR fixes it.

**Comment by djowel** [comment]
> What's the likelihood of this being merged? Unordered right now has a lot of output from `-Wconversion` + `tuple.hpp` and this PR fixes it.

It looks good to me, except of the CI issues. Is this something you can look at?

**Comment by LeonineKing1199** [comment]
Ah, I think I know the issues with the CI here.

Unfortunately, GitHub Actions doesn't seem to give helpful error messages but they've deprecated Ubuntu 16.04 which this repo is configured to use.

Sam's PRs for this repo should fix the issue but I'm wondering if we don't have some robust GHA/Drone scripts sitting around in some of the other repos.

**Comment by pdimov** [comment]
I merged Sam's PR fixing GHA, but this PR needs to be rebased against develop to acquire those fixes.

**Comment by pdimov** [comment]
Here's a GHA run of this PR merged into the current develop: https://github.com/boostorg/tuple/actions/runs/1468081170

**Comment by igaztanaga** [comment]
Sorry for the delay, I just forgot to rebase the patch against develop. Seems like all checks are ok now, could we merge?

**Comment by igaztanaga** [comment]
Many thanks!

**Pull request merged**
